[jobs/backup]Feat: delete Dropbox backups older than 30 days
metakgp/metakgp-wiki pull request #127
Opened 2024-02-13 19:50 UTC by shikharish

2024-02-13 21:22 UTC, harshkhandeparkar requested changes

2024-02-13 21:22 UTC, harshkhandeparkar commented on jobs/crontab
> +23 4 * * * /root/backup/rotate_backups.sh >> /var/log/cron.log 2>&1
Can we have separate log files for these? Also, do we rotate these logs?

2024-02-13 21:22 UTC, harshkhandeparkar commented on jobs/backup/rotate_backups.py
> +backup_folder_path = ""
If these are constants, it would be better to name them in all caps.

2024-02-15 14:56 UTC, harshkhandeparkar requested changes

2024-02-15 14:56 UTC, harshkhandeparkar commented on jobs/backup/rotate_backups.py
> +now = datetime.datetime.now()
This is also a constant right?

2024-02-15 14:56 UTC, harshkhandeparkar commented on jobs/backup/rotate_backups.py
> +    if days_old > 30:
Should we also check for the number of files left? If the backup job fails for some reason, over time this job will delete all backup files.

2024-03-09 20:49 UTC, harshkhandeparkar approved these changes
"Jai Shree Ram! chal jayega"
\- Shikhar

2024-03-09 20:53 UTC, rajivharlalka approved these changes

2024-03-09 20:54 UTC, merged