Create MetaMaint.py
metakgp/metakgp-wiki pull request #40
Opened 2018-03-29 07:29 UTC by TheMousePotato

TODO:
* Add Random_package template to sidebar of homepage(which I don't have access)
* Deploy and make it run once in a day.

2018-03-29 11:09 UTC, amrav approved these changes
Great, thanks for doing this! You could add the cron config into this PR too if you like.

2018-03-29 11:09 UTC, amrav commented on jobs/pywikibot/scripts/MetaMaint.py
> +    rpage = pywikibot.Page(site, 'Package_blurbs')
Nit: probably better to put this under the `Metakgp` namespace, like `Metakgp:Package_blurbs`, so it doesn't show up in recent pages, trending, etc.

2018-03-29 11:24 UTC, icyflame approved these changes
I made a test page to see how this would look [here](https://wiki.metakgp.org/w/User:Icyflame/main_page_testing)

2018-03-29 11:25 UTC, icyflame commented
Will merge this PR tonight, if there are no other comments. (We need to edit the Main page HTML to put this template somewhere)

cc @amrav

2018-03-29 11:27 UTC, icyflame requested changes
@TheMousePotato You still need to add the bash script that will run this script, and the line in the crontab. I think we should merge this once we have both of those things.

2018-03-29 11:29 UTC, icyflame commented
Preview:

![image](https://user-images.githubusercontent.com/3668034/38086594-9616cb5c-3372-11e8-8f6e-796761637dbd.png)

2018-03-29 11:36 UTC, amrav commented
Why not feature it on the main column? The sidebar is getting too busy, we shouldn't put more than three things in there. Would be great to add screenshots as well.

Once a day also seems too frequent for updates, perhaps once every three days or once a week will allow each featured project to get more visibility.

Improvement for a future PR: can we do better than random selection, perhaps weighting projects by [frecency](https://en.wikipedia.org/wiki/Frecency) of commit activity?

2018-03-29 11:41 UTC, amrav commented
Forgot to ask, @TheMousePotato could you attach a log of a successful run, to show that it actually works?

2018-03-29 16:50 UTC, icyflame commented
Hey @TheMousePotato I have closed #41 and #42. Please make the changes inside this PR itself.

2018-03-30 18:51 UTC, TheMousePotato commented
![screenshot from 2018-03-31 00-16-42](https://user-images.githubusercontent.com/33940798/38149709-3f9cad84-3479-11e8-8648-a310e61be79f.png)

@amrav You were talking about this template, right?

2018-04-12 05:46 UTC, icyflame commented
Hey @TheMousePotato can you add all the files in this PR so that we can go ahead and merge this?

2018-04-12 07:02 UTC, TheMousePotato commented
@icyflame Added all files.

2018-04-12 12:43 UTC, icyflame approved these changes

2018-04-12 12:44 UTC, merged